package com.imaginea.komparator.engine;

public enum DifferenceType
	{
	MISSING_REQUIRED_NODE, IMPROPER_NODE_ORDER, MISSING_REQUIRED_ATTRIBUTE, MISMATCHED_ATTRIBUTE_VALUE, IMPROPER_ATTRIBUTE_ORDER
	}
